pipeline {
    agent {
        docker {
            image 'python:3.9'
        }
    }

    stages {
        stage("clone repo") {
            steps {
                echo "Cloning repository"
            }
        }

        stage("run app") {
            steps {
                dir('docker-agent-demo'){
                sh "python --version"
                sh "python app.py"
                }
            }
        }
    }
}


